# Generated by Django 5.2.8 on 2025-11-23 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название проекта"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=1280, verbose_name="Ширина холста (px)"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=720, verbose_name="Высота холста (px)"
                    ),
                ),
                (
                    "fps",
                    models.PositiveIntegerField(
                        default=12, verbose_name="Кадров в секунду"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="animation_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Frame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(verbose_name="Номер кадра")),
                (
                    "content_json",
                    models.TextField(blank=True, verbose_name="JSON содержимого кадра"),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="frames/",
                        verbose_name="Превью кадра",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frames",
                        to="animation.animationproject",
                    ),
                ),
            ],
            options={
                "ordering": ["project", "index"],
                "unique_together": {("project", "index")},
            },
        ),
    ]
