# Generated by Django 5.2.8 on 2026-03-31 09:07

import animation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0002_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationproject',
            name='main_audio',
            field=models.FileField(blank=True, null=True, upload_to=animation.models.project_main_audio_upload_to, verbose_name='Основная аудиодорожка'),
        ),
        migrations.AddField(
            model_name='animationproject',
            name='main_audio_duration',
            field=models.FloatField(blank=True, null=True, verbose_name='Длительность аудио (секунды)'),
        ),
        migrations.AddField(
            model_name='animationproject',
            name='main_audio_start_frame',
            field=models.PositiveIntegerField(default=1, verbose_name='Стартовый кадр аудио'),
        ),
    ]
