# Generated by Django 5.2.8 on 2026-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0003_animationproject_main_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='animationproject',
            name='main_audio_segments',
            field=models.JSONField(blank=True, default=list, verbose_name='Audio segments'),
        ),
    ]
