# Generated by Django 5.2.8 on 2026-04-18 20:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animation', '0007_projectpresencesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('last_heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frame_lock', to='animation.frame')),
                ('presence_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frame_locks', to='animation.projectpresencesession')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_locks', to='animation.animationproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frame_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'expires_at'], name='animation_f_project_0d9a2b_idx'), models.Index(fields=['project', 'user'], name='animation_f_project_2c3f0a_idx')],
            },
        ),
    ]
